# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Balanced oracle
#'
#' Computes the balanced oracle index.
#'
#' @param lambda Vector of decreasing, strictly positive entries of the
#'   diagonal design matrix.
#' @param mu Vector valued input signal.
#' @param delta Strictly positive level of random noise.
#' @param alpha Numeric smoothing parameter.
#' @param filt Character string giving the filter to be used.
#'
#' @return Returns the strong balanced oracle index as an integer.
#'
#' @export
balOracle <- function(lambda, mu, delta, alpha = -1.0, filt = "cutoff") {
    .Call(`_rlystop_balOracle`, lambda, mu, delta, alpha, filt)
}

#' Classical oracle
#'
#' Computes the classical oracle index.
#'
#' @param lambda Vector of decreasing, strictly positive entries of the
#'   diagonal design matrix.
#' @param mu Vector valued input signal.
#' @param delta Strictly positive level of random noise.
#' @param filt Character string giving the filter to be used. This must match
#'   one of "cutoff".
#' @param alpha Numeric smoothing parameter.
#'
#' @return Returns the classical oracle index as an integer.
#'
#' @export
claOracle <- function(lambda, mu, delta, alpha = -1, filt = "cutoff") {
    .Call(`_rlystop_claOracle`, lambda, mu, delta, alpha, filt)
}

#' Landweber iteration
#'
#' Computes the Landweber iteration for a diagon
#' 
#' @param m Integer stopping index. 
#' @param Y Numeric vector of observed data.
#' @param lambda Numeric vector of decreasing, strictly positive entries of
#'   the diagonal design matrix.
#'
#' @return Returns the m-th iterate of the Landweber iteration.
#'
landw <- function(m, Y, lambda) {
    .Call(`_rlystop_landw`, m, Y, lambda)
}

#' Residual stopping time
#'
#' Computes the residual based stopping time for a given data
#' vector \code{Y} and a given diagonal design matrix \code{lambda}.
#'
#' @param Y Numeric vector of observed data.
#' @param lambda Numeric vector of decreasing, strictly positive entries of the
#'   diagonal design matrix.
#' @param alpha Numeric smoothing index for the residuals.
#' @param kappa Strictly positive stopping value.
#' @param filt Character string giving the filter to be used.
#'
#' @return Returns the integer value of the smoothed residual based stopping
#'   time.
#'
#' @export
sTime <- function(Y, lambda, alpha, kappa, filt = "cutoff") {
    .Call(`_rlystop_sTime`, Y, lambda, alpha, kappa, filt)
}

