# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Balanced oracle 
#' 
#' Computes the balanced oracle time. 
#'
#' @param lambda Vector of decreasing, strictly positive entries of the
#'   diagonal design matrix.
#' @param mu Vector valued input signal. 
#' @param delta Strictly positive level of random noise.
#' @param alpha Numeric smoothing parameter.
#' @param filt Character string giving the filter to be used.
#'
#' @return Returns the strong balanced oracle time as an integer.
#'
#' @export
balOracle <- function(lambda, mu, delta, alpha = -1.0, filt = "cutoff") {
    .Call(`_rlystop_balOracle`, lambda, mu, delta, alpha, filt)
}

#' Squared bias
#' 
#' Computes the squared bias of the filter estimator a given diagonal design
#' matrix \code{lambda} and signal ' \code{mu}.
#'
#' @param lambda Vector of decreasing, strictly positive entries of the
#'   diagonal design matrix.
#' @param mu Vector valued input signal. 
#' @param alpha Numeric smoothing parameter.
#' @param filt Character string giving the filter to be used.
#'
#' @return Returns all values of the squared bias in a double vector.
#'
#' @export
bias2 <- function(lambda, mu, alpha = -1.0, filt = "cutoff") {
    .Call(`_rlystop_bias2`, lambda, mu, alpha, filt)
}

#' Classical oracle
#'
#' Computes the classical oracle time.
#'
#' @param lambda Vector of decreasing, strictly positive entries of the
#'   diagonal design matrix.
#' @param mu Vector valued input signal.
#' @param delta Strictly positive level of random noise.
#' @param filt Character string giving the filter to be used. This must match
#'   one of "cutoff".
#' @param alpha Numeric smoothing parameter.
#'
#' @return Returns the classical oracle time as an integer.
#'
#' @export
cla_oracle <- function(lambda, mu, delta, alpha = -1, filt = "cutoff") {
    .Call(`_rlystop_cla_oracle`, lambda, mu, delta, alpha, filt)
}

#' Residual stopping time
#'
#' Computes the residual based stopping time for a given data
#' vector \code{Y} and a given diagonal design matrix \code{lambda}.
#'
#' @param Y Numeric vector of observed data.
#' @param lambda Numeric vector of decreasing, strictly positive entries of the
#'   diagonal design matrix.
#' @param alpha Numeric smoothing index for the residuals.
#' @param kappa Strictly positive stopping value.
#' @param filt Character string giving the filter to be used.
#'
#' @return Returns the integer value of the smoothed residual based stopping
#'   time.
#'
#' @export
sTime <- function(Y, lambda, alpha, kappa, filt = "cutoff") {
    .Call(`_rlystop_sTime`, Y, lambda, alpha, kappa, filt)
}

#' Variance
#' 
#' Computes the variance of the filter estimator a given diagonal design
#' matrix \code{lambda} and noise level delta.
#'
#' @param lambda Vector of decreasing, strictly positive entries of the
#'   diagonal design matrix.
#' @param delta Numeric noise level.
#' @param alpha Numeric smoothing parameter.
#' @param filt Character string giving the filter to be used.
#'
#' @return Returns all values of the variancee in a double vector.
#'
#' @export
variance <- function(lambda, delta, alpha = -1.0, filt = "cutoff") {
    .Call(`_rlystop_variance`, lambda, delta, alpha, filt)
}

